name: Build & Push Ray Logs Sidecar Image

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - .github/workflows/ray-logs-sidecar.yml
      - ray-logs-sidecar/**
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [ray-logs-sidecar]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v2
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: image-names
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.container }}
          tags: |
            type=raw,value=latest,enable=${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
            type=sha,format=long
      - uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.container }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: ${{ steps.image-names.outputs.tags }}
